### PR TITLE
Adapt to KiCad6.0.0

### PR DESCRIPTION
**Pull request by sekigon-gonnoc**
Tested on KiCad 6.0.0, Windows10  64bit

### CODE REVIEW

**Comment by hsgw** [comment]
Working perfectly on kicad6.0.0, win11 64bit too.
Thanks.

**Comment by BenRoe** [comment]
Can also confirm, it works on OSX with Kicad 6.0.0

**Comment by AndrewKeene** [comment]
Also confirming, all good on Win11 64-bit, KiCad 6.0.0 release.  Thank you.

**Comment by pierrotm777** [comment]
Can you say me how to install it with 6.0 please ?
Thanks

**Comment by WhiteChairFromIkea** [comment]
In pcb editor: tools -> open pligins directory, copy plugin there, restart pcbeditor

**Comment by kb-elmo** [comment]
Nice work.

Though I found that this creates very very small teardrops on rounded traces.
Is there any way to make these larger or follow the rounded trace further?

image

**Comment by pierrotm777** [comment]
WhiteChairFromIkea,

I have tried your method without success.
path
plugins

**Comment by kb-elmo** [comment]
> WhiteChairFromIkea,
> 
> I have tried your method without success.

The new path for the KiCAD plugins in version 6 is <userhome>\Documents\KiCAD\6.0\scripting\plugins

**Comment by WhiteChairFromIkea** [comment]
> WhiteChairFromIkea,
> 
> I have tried your method without success. path plugins

Maybe you tried to install v5-only compatible branch? You need to use v5,99 branch (as posted here https://forum.kicad.info/t/yet-another-python-teardrop-script-adds-and-deletes-teardrops-to-a-pcb-v0-3-3/3388/101?u=poco)

**Comment by NilujePerchut** [comment]
Hi all
@sekigon-gonnoc : I was planning to merge my V5.99 branch  into master to make Kicad V6 the new default when I saw your pull request. 
From what I see, it seems to do the same as my V5.99 branch. Can you tell me if you pull request does something more (not in the 5.99 branch) ?
If not, I will merge the branch and discard both pending pull requests on the same subject

**Comment by NilujePerchut** [comment]
@kb-elmo : I will try to look at the problem (teardrops on rounded tracks). But cannot guaranty anything due to my very little bandwidth for that on the moment.

**Comment by sekigon-gonnoc** [comment]
@NilujePerchut I found difference in `teardrop_gui.py`.
This PR can fix dialog layout. KiCad 6 probably changed `wx.DefaultSize` from KiCad 5.99.
Please close this pull request after updating gui of V5.99 branch because some changes in td.py are conflicting.

**Comment by NilujePerchut** [comment]
V6 in now supported in the master branch

**Pull request closed without merging**
